import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
component ButtonUp inherits Rectangle {
    in-out property text <=> txt.text;
    callback clicked <=> touch.clicked;
    border-radius: 5px;
    background: #0c9c4c;
    //touch.pressed ? #4CACAC  : touch.has-hover ? #50d98e :  #0C9C4C;
    height: 10%;
    width: 5%;
    txt := Text {
        font-size: 15px;
        height: 90%;
        width: 60%;
        color: touch.pressed ? #fff : #eee;
    }

    touch := TouchArea { }
}
component ButtonDown inherits Rectangle {
    in-out property text <=> txt.text;
    callback clicked <=> touch.clicked;
    border-radius: 5px;
    background: #9c0c0c;
    //touch.pressed ? #4CACAC  : touch.has-hover ? #50d98e :  #0C9C4C;
    height: 10%;
    width: 5%;
    txt := Text {
        font-size: 15px;
        height: 90%;
        width: 60%;
        color: touch.pressed ? #fff : #eee;
    }

    touch := TouchArea { }
}

export component AppWindow inherits Window {
    preferred-width: 1800px;
    preferred-height: 900px;
    background: #363D4A;
    title: "CMP - CLIENTE";
    always-on-top: true;
    in-out property <int> counter: 42;
    in-out property <string> estado: "";
    in-out property <bool> visibilidad: true;
    // Definición de propiedades para una lista de 10 objetos
    in-out property <string> nombre_c01: "nombre_c01";
    in-out property <string> artista_c01: "artista_c01";
    in-out property <string> guid_c01: "guid_c01";

    in-out property <string> nombre_c02: "nombre_c02";
    in-out property <string> artista_c02: "artista_c02";
    in-out property <string> guid_c02: "guid_c02";

    in-out property <string> nombre_c03: "nombre_c03";
    in-out property <string> artista_c03: "artista_c03";
    in-out property <string> guid_c03: "guid_c03";

    in-out property <string> nombre_c04: "nombre_c04";
    in-out property <string> artista_c04: "artista_c04";
    in-out property <string> guid_c04: "guid_c04";

    in-out property <string> nombre_c05: "nombre_c05";
    in-out property <string> artista_c05: "artista_c05";
    in-out property <string> guid_c05: "guid_c05";

    in-out property <string> nombre_c06: "nombre_c06";
    in-out property <string> artista_c06: "artista_c06";
    in-out property <string> guid_c06: "guid_c06";

    in-out property <string> nombre_c07: "nombre_c07";
    in-out property <string> artista_c07: "artista_c07";
    in-out property <string> guid_c07: "guid_c07";

    in-out property <string> nombre_c08: "nombre_c08";
    in-out property <string> artista_c08: "artista_c08";
    in-out property <string> guid_c08: "guid_c08";

    in-out property <string> nombre_c09: "nombre_c09";
    in-out property <string> artista_c09: "artista_c09";
    in-out property <string> guid_c09: "guid_c09";

    in-out property <string> nombre_c10: "nombre_c10";
    in-out property <string> artista_c10: "artista_c10";
    in-out property <string> guid_c10: "guid_c10";

    in-out property <string> tempguid: "";

    callback request-increase-value();
    callback request-vote-up();
    callback request-vote-down();


    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: center;
            listamusica := Rectangle {
                height: 95%;
                width: 95%;
                background: #FFFFFF;
                border-radius: 5px;
                visible: !root.visibilidad;
                VerticalLayout {
                    alignment: LayoutAlignment.start;
                    HorizontalBox {
                        cancion01 := Rectangle {
                            height: 10%;
                            width: 95%;
                            HorizontalLayout {
                                alignment: LayoutAlignment.space-around;
                                Text {
                                    text: root.nombre_c01;
                                }
                                Text {
                                    text: root.nombre_c01;
                                }
                                ButtonUp {
                                    text: "+";
                                    clicked => {
                                        root.tempguid=guid_c01;
                                        root.request-vote-up();
                                     }
    
                                }
                                ButtonDown {
                                    text: "-";
                                    clicked => {
                                        root.tempguid=guid_c01;
                                        root.request-vote-down();
                                     }
                                }
                            }
                        }
                    }

                    HorizontalBox {
                        cancion02 := Rectangle {
                            height: 10%;
                            width: 95%;
                            HorizontalLayout {
                                alignment: LayoutAlignment.space-around;
                                Text {
                                    text: root.nombre_c02;
                                }
                                Text {
                                    text: root.nombre_c02;
                                }
                                ButtonUp {
                                    text: "+";
                                    clicked => {
                                        root.tempguid=guid_c02;
                                        root.request-vote-up();
                                     }
    
                                }
                                ButtonDown {
                                    text: "-";
                                    clicked => {
                                        root.tempguid=guid_c02;
                                        root.request-vote-down();
                                     }
                                }
                            }
                        }
                    }

                    HorizontalBox {
                        cancion03 := Rectangle {
                            height: 10%;
                            width: 95%;
                            HorizontalLayout {
                                alignment: LayoutAlignment.space-around;
                                Text {
                                    text: root.nombre_c03;
                                }
                                Text {
                                    text: root.nombre_c03;
                                }
                                ButtonUp {
                                    text: "+";
                                    clicked => {
                                        root.tempguid=guid_c03;
                                        root.request-vote-up();
                                     }
    
                                }
                                ButtonDown {
                                    text: "-";
                                    clicked => {
                                        root.tempguid=guid_c03;
                                        root.request-vote-down();
                                     }
                                }
                            }
                        }
                    }

                    HorizontalBox {
                        cancion04 := Rectangle {
                            height: 10%;
                            width: 95%;
                            HorizontalLayout {
                                alignment: LayoutAlignment.space-around;
                                Text {
                                    text: root.nombre_c04;
                                }
                                Text {
                                    text: root.nombre_c04;
                                }
                                ButtonUp {
                                    text: "+";
                                    clicked => {
                                        root.tempguid=guid_c04;
                                        root.request-vote-up();
                                     }
    
                                }
                                ButtonDown {
                                    text: "-";
                                    clicked => {
                                        root.tempguid=guid_c04;
                                        root.request-vote-down();
                                     }
                                }
                            }
                        }
                    }

                    HorizontalBox {
                        cancion05 := Rectangle {
                            height: 10%;
                            width: 95%;
                            HorizontalLayout {
                                alignment: LayoutAlignment.space-around;
                                Text {
                                    text: root.nombre_c05;
                                }
                                Text {
                                    text: root.nombre_c05;
                                }
                                ButtonUp {
                                    text: "+";
                                    clicked => {
                                        root.tempguid=guid_c05;
                                        root.request-vote-up();
                                     }
    
                                }
                                ButtonDown {
                                    text: "-";
                                    clicked => {
                                        root.tempguid=guid_c05;
                                        root.request-vote-down();
                                     }
                                }
                            }
                        }
                    }

                    HorizontalBox {
                        cancion06 := Rectangle {
                            height: 10%;
                            width: 95%;
                            HorizontalLayout {
                                alignment: LayoutAlignment.space-around;
                                Text {
                                    text: root.nombre_c06;
                                }
                                Text {
                                    text: root.nombre_c06;
                                }
                                ButtonUp {
                                    text: "+";
                                    clicked => {
                                        root.tempguid=guid_c06;
                                        root.request-vote-up();
                                     }
    
                                }
                                ButtonDown {
                                    text: "-";
                                    clicked => {
                                        root.tempguid=guid_c06;
                                        root.request-vote-down();
                                     }
                                }
                            }
                        }
                    }

                    HorizontalBox {
                        cancion07 := Rectangle {
                            height: 10%;
                            width: 95%;
                            HorizontalLayout {
                                alignment: LayoutAlignment.space-around;
                                Text {
                                    text: root.nombre_c07;
                                }
                                Text {
                                    text: root.nombre_c07;
                                }
                                ButtonUp {
                                    text: "+";
                                    clicked => {
                                        root.tempguid=guid_c07;
                                        root.request-vote-up();
                                     }
    
                                }
                                ButtonDown {
                                    text: "-";
                                    clicked => {
                                        root.tempguid=guid_c07;
                                        root.request-vote-down();
                                     }
                                }
                            }
                        }
                    }

                    HorizontalBox {
                        cancion08 := Rectangle {
                            height: 10%;
                            width: 95%;
                            HorizontalLayout {
                                alignment: LayoutAlignment.space-around;
                                Text {
                                    text: root.nombre_c08;
                                }
                                Text {
                                    text: root.nombre_c08;
                                }
                                ButtonUp {
                                    text: "+";
                                    clicked => {
                                        root.tempguid=guid_c08;
                                        root.request-vote-up();
                                     }
    
                                }
                                ButtonDown {
                                    text: "-";
                                    clicked => {
                                        root.tempguid=guid_c08;
                                        root.request-vote-down();
                                     }
                                }
                            }
                        }
                    }

                    HorizontalBox {
                        cancion09 := Rectangle {
                            height: 10%;
                            width: 95%;
                            HorizontalLayout {
                                alignment: LayoutAlignment.space-around;
                                Text {
                                    text: root.nombre_c09;
                                }
                                Text {
                                    text: root.nombre_c09;
                                }
                                ButtonUp {
                                    text: "+";
                                    clicked => {
                                        root.tempguid=guid_c09;
                                        root.request-vote-up();
                                     }
    
                                }
                                ButtonDown {
                                    text: "-";
                                    clicked => {
                                        root.tempguid=guid_c09;
                                        root.request-vote-down();
                                     }
                                }
                            }
                        }
                    }

                    HorizontalBox {
                        cancion10 := Rectangle {
                            height: 10%;
                            width: 95%;
                            HorizontalLayout {
                                alignment: LayoutAlignment.space-around;
                                Text {
                                    text: root.nombre_c10;
                                }
                                Text {
                                    text: root.nombre_c10;
                                }
                                ButtonUp {
                                    text: "+";
                                    clicked => {
                                        root.tempguid=guid_c10;
                                        root.request-vote-up();
                                     }
    
                                }
                                ButtonDown {
                                    text: "-";
                                    clicked => {
                                        root.tempguid=guid_c10;
                                        root.request-vote-down();
                                     }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
